import json
import os

def update_translation():
    file_path = 'client/src/locales/en/translation.json'
    
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    terms_page_data = {
        "title": "Terms of Service",
        "lastUpdated": "Last Updated: November 11, 2025 • Version 2.0",
        "providedBy": "Provided by",
        "sections": {
            "agreement": {
                "title": "1. Agreement to Terms",
                "content1": "By accessing, downloading, installing, or using Log & Ledger Pro (\"the Platform\", \"the Software\", \"the Service\"), you agree to be bound by these Terms of Service (\"Terms\", \"Agreement\"). This is a legally binding contract between you (\"User\", \"you\", \"your\") and TibrCode Software Development (\"TibrCode\", \"we\", \"us\", \"our\").",
                "content2": "<strong>IF YOU DO NOT AGREE TO THESE TERMS, DO NOT USE THIS SOFTWARE.</strong> Your continued use of the Platform constitutes your acceptance of these Terms and any subsequent modifications.",
                "noticeTitle": "Important Notice:",
                "noticeContent": "These Terms apply to all users worldwide, including individuals, businesses, organizations, and governmental entities."
            },
            "serviceDescription": {
                "title": "2. Service Description",
                "intro": "Log & Ledger Pro is a comprehensive cloud-based accounting and business management software platform that provides:",
                "items": [
                    "Financial accounting and bookkeeping tools",
                    "Invoicing, billing, and payment management",
                    "Expense tracking and bank reconciliation",
                    "Financial reports and analytics",
                    "Inventory and warehouse management",
                    "Tax calculation and reporting features",
                    "Multi-currency and multi-language support",
                    "Cloud data storage and backup"
                ],
                "professionalSoftware": {
                    "title": "Professional Software Platform:",
                    "content": "Log & Ledger Pro is comprehensive business management software designed and developed by TibrCode Software Development."
                }
            },
            "natureOfService": {
                "title": "3. Nature of Service & Important Disclaimers",
                "critical": {
                    "title": "CRITICAL: Please Read Carefully",
                    "intro": "<strong>3.1 Software Tool Only:</strong> Log & Ledger Pro is accounting <strong>SOFTWARE</strong> only. It is NOT:",
                    "items": [
                        "An accounting firm, CPA firm, or professional accounting service",
                        "A tax preparation service or tax advisory firm",
                        "A legal advisory service or law firm",
                        "A financial advisory service or investment advisor",
                        "A substitute for professional accountants, auditors, tax advisors, or legal counsel"
                    ]
                },
                "noAdvice": {
                    "title": "3.2 No Professional Advice:",
                    "content": "The Software provides tools for recording, organizing, and reporting financial data. It does NOT provide, and should not be construed as providing, professional accounting, tax, legal, financial, or investment advice. Any calculations, reports, or outputs generated by the Software are based solely on the data you input and the formulas/logic programmed into the Software."
                },
                "userResponsibility": {
                    "title": "3.3 User Responsibility:",
                    "intro": "You are solely responsible for:",
                    "items": [
                        "The accuracy, completeness, and legality of all data entered into the Software",
                        "Interpreting and using the outputs, reports, and calculations generated by the Software",
                        "Ensuring compliance with all applicable laws, regulations, accounting standards, and tax requirements",
                        "Consulting with qualified, licensed professionals (accountants, CPAs, tax advisors, lawyers) for specific advice",
                        "Verifying the accuracy of all calculations and reports before relying on them for business or tax purposes"
                    ]
                },
                "consultation": {
                    "title": "⚠️ MANDATORY PROFESSIONAL CONSULTATION:",
                    "content": "TibrCode strongly recommends that you consult with qualified, licensed professionals including certified accountants, tax advisors, auditors, and legal counsel for matters requiring specialized expertise, regulatory compliance, tax planning, financial audits, and legal opinions. Software cannot replace human professional judgment and expertise."
                }
            },
            "userResponsibilities": {
                "title": "4. User Responsibilities & Obligations",
                "accountSecurity": {
                    "title": "4.1 Account Security",
                    "content": "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account."
                },
                "dataAccuracy": {
                    "title": "4.2 Data Accuracy",
                    "content": "You warrant that all data you enter into the Software is accurate, complete, and lawful. You are solely responsible for any errors, omissions, or inaccuracies in your data."
                },
                "legalCompliance": {
                    "title": "4.3 Legal Compliance",
                    "intro": "You agree to comply with all applicable local, national, and international laws, regulations, and accounting standards, including but not limited to:",
                    "items": [
                        "Tax laws and filing requirements",
                        "Accounting standards (GAAP, IFRS, or local standards)",
                        "Data protection and privacy laws (GDPR, CCPA, etc.)",
                        "Anti-money laundering (AML) and know-your-customer (KYC) regulations",
                        "Financial reporting and disclosure requirements"
                    ]
                },
                "prohibitedUses": {
                    "title": "4.4 Prohibited Uses",
                    "intro": "You agree NOT to:",
                    "items": [
                        "Use the Software for any illegal, fraudulent, or unauthorized purpose",
                        "Reverse engineer, decompile, or attempt to extract the source code",
                        "Resell, redistribute, or sublicense the Software without written permission",
                        "Use the Software to process data belonging to third parties without proper authorization",
                        "Overload, hack, or disrupt the Software infrastructure"
                    ]
                }
            },
            "limitationOfLiability": {
                "title": "5. Limitation of Liability",
                "legalLimitation": {
                    "title": "IMPORTANT LEGAL LIMITATION:",
                    "intro": "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, TIBRCODE SOFTWARE DEVELOPMENT, ITS DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AND LICENSORS SHALL NOT BE LIABLE FOR:",
                    "items": [
                        "Any indirect, incidental, consequential, special, exemplary, or punitive damages",
                        "Loss of profits, revenue, data, goodwill, or business opportunities",
                        "Tax penalties, fines, interest, or audits resulting from your use of the Software",
                        "Errors, omissions, or inaccuracies in calculations, reports, or data outputs",
                        "Business interruption, data loss, or system failures",
                        "Decisions made based on Software outputs without professional verification"
                    ]
                },
                "maximumLiability": {
                    "title": "5.1 Maximum Liability:",
                    "content": "In no event shall TibrCode's total liability to you for all claims arising from or related to the Software exceed the amount you paid to TibrCode for the Software in the 12 months preceding the claim, or $100 USD, whichever is greater."
                },
                "basisOfBargain": {
                    "title": "5.2 Basis of the Bargain:",
                    "content": "You acknowledge that TibrCode has set its prices and entered into this Agreement in reliance upon the limitations of liability and the disclaimers of warranties set forth herein, and that the same form an essential basis of the bargain between the parties."
                }
            },
            "warranties": {
                "title": "6. Warranties and Disclaimer",
                "disclaimer": "THE SOFTWARE IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, OR RELIABILITY.",
                "noWarranties": {
                    "intro": "TibrCode does not warrant that:",
                    "items": [
                        "The Software will meet your specific requirements or expectations",
                        "The Software will be uninterrupted, timely, secure, or error-free",
                        "The results obtained from the Software will be accurate, complete, or reliable",
                        "All errors or defects will be corrected",
                        "The Software complies with all laws and regulations in your jurisdiction"
                    ]
                }
            },
            "intellectualProperty": {
                "title": "7. Intellectual Property Rights",
                "ownership": {
                    "title": "7.1 Ownership:",
                    "content": "The Software, including all code, features, functionality, designs, logos, and documentation, is owned by TibrCode Software Development and is protected by international copyright, trademark, patent, trade secret, and other intellectual property laws."
                },
                "license": {
                    "title": "7.2 License Grant:",
                    "content": "Subject to your compliance with these Terms, TibrCode grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Software for your internal business purposes."
                },
                "userData": {
                    "title": "7.3 User Data:",
                    "content": "You retain all rights to the data you input into the Software. By using the Software, you grant TibrCode a license to process, store, and backup your data solely for the purpose of providing the Service."
                }
            },
            "termination": {
                "title": "8. Termination",
                "byYou": {
                    "title": "8.1 By You:",
                    "content": "You may terminate your use of the Software at any time by ceasing all use and deleting your account."
                },
                "byTibrCode": {
                    "title": "8.2 By TibrCode:",
                    "content": "TibrCode may suspend or terminate your access to the Software immediately, without notice, if you breach these Terms, engage in prohibited activities, or for any other reason at TibrCode's sole discretion."
                },
                "effect": {
                    "title": "8.3 Effect of Termination:",
                    "content": "Upon termination, your right to use the Software ceases immediately. Sections relating to intellectual property, disclaimers, limitation of liability, and dispute resolution survive termination."
                }
            },
            "modifications": {
                "title": "9. Modifications to Terms and Service",
                "content": "TibrCode reserves the right to modify, update, discontinue, or change these Terms and the Software at any time without prior notice. Continued use of the Software after such changes constitutes acceptance of the modified Terms."
            },
            "governingLaw": {
                "title": "10. Governing Law & Dispute Resolution",
                "law": {
                    "title": "10.1 Governing Law:",
                    "content": "These Terms shall be governed by and construed in accordance with the laws of the jurisdiction where TibrCode Software Development is registered, without regard to conflict of law principles."
                },
                "dispute": {
                    "title": "10.2 Dispute Resolution:",
                    "content": "Any dispute arising from these Terms shall first be attempted to be resolved through good faith negotiation. If unresolved, disputes shall be subject to binding arbitration or litigation in the courts of TibrCode's jurisdiction."
                }
            },
            "generalProvisions": {
                "title": "11. General Provisions",
                "entireAgreement": {
                    "title": "11.1 Entire Agreement:",
                    "content": "These Terms constitute the entire agreement between you and TibrCode."
                },
                "severability": {
                    "title": "11.2 Severability:",
                    "content": "If any provision is found invalid, the remaining provisions remain in full force."
                },
                "waiver": {
                    "title": "11.3 Waiver:",
                    "content": "Failure to enforce any provision does not constitute a waiver of that provision."
                },
                "assignment": {
                    "title": "11.4 Assignment:",
                    "content": "You may not assign these Terms without TibrCode's written consent."
                }
            },
            "contact": {
                "title": "12. Contact Information",
                "intro": "For questions about these Terms, please contact:",
                "details": {
                    "company": "TibrCode Software Development",
                    "email": "Email: legal@tibrcode.com",
                    "support": "Support: support@logandledger.com"
                }
            }
        },
        "footer": {
            "rights": "© {{year}} TibrCode Software Development. All rights reserved.",
            "trademark": "Log & Ledger Pro is a trademark of TibrCode Software Development."
        }
    }
    
    data['termsPage'] = terms_page_data
    
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print("Successfully updated translation.json with termsPage data")

if __name__ == "__main__":
    update_translation()
