import json
import os

def update_translation():
    file_path = 'client/src/locales/en/translation.json'
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Error: File not found at {file_path}")
        return
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON in {file_path}")
        return

    disclaimer_data = {
        "title": "Disclaimer",
        "lastUpdated": "Last Updated: November 11, 2025 • Version 2.0",
        "providedBy": "Provided by",
        "companyName": "TibrCode Software Development",
        "sections": {
            "importantInfo": {
                "title": "1. Important Information",
                "criticalDisclaimer": "⚠️ READ CAREFULLY - CRITICAL DISCLAIMER",
                "softwareOnly": "Log & Ledger Pro is ACCOUNTING SOFTWARE ONLY.",
                "notSubstitute": "It is NOT a substitute for professional accounting, tax, legal, or financial advisory services. This software provides tools for recording and organizing financial data, but does NOT provide professional advice or services.",
                "acknowledgment": "By using Log & Ledger Pro, you acknowledge and agree that:",
                "points": [
                    "The software is a technological tool, not a professional service provider",
                    "TibrCode Software Development is a software company, not an accounting firm, tax advisor, or legal consultant",
                    "All outputs, calculations, and reports are based solely on data you input",
                    "You are solely responsible for verifying accuracy and compliance with applicable laws",
                    "You must consult qualified professionals for specialized advice and regulatory compliance"
                ]
            },
            "serviceDefinition": {
                "title": "2. Service Definition",
                "whatWeProvide": {
                    "title": "✓ What We Provide",
                    "points": [
                        "<strong>Software Tools:</strong> Technology for recording financial transactions",
                        "<strong>Data Organization:</strong> Systems to structure and categorize your business data",
                        "<strong>Report Generation:</strong> Automated creation of financial reports from your data",
                        "<strong>Calculations:</strong> Mathematical computations based on programmed formulas",
                        "<strong>Cloud Storage:</strong> Secure storage and backup of your data",
                        "<strong>Features:</strong> Invoicing, expense tracking, banking, inventory management"
                    ]
                },
                "whatWeAreNot": {
                    "title": "❌ What We Are NOT",
                    "points": [
                        "<strong>NOT an Accounting Firm:</strong> We don't provide accounting services or certified audits",
                        "<strong>NOT a CPA/Chartered Accountant:</strong> We don't offer professional accounting advice",
                        "<strong>NOT a Tax Advisor:</strong> We don't provide tax planning, preparation, or advice",
                        "<strong>NOT a Legal Advisor:</strong> We don't offer legal counsel or interpretation of laws",
                        "<strong>NOT Financial Advisors:</strong> We don't provide investment or financial planning advice",
                        "<strong>NOT Auditors:</strong> We don't perform financial audits or attestation services"
                    ]
                },
                "keyDistinction": {
                    "title": "Key Distinction:",
                    "text": "Log & Ledger Pro is a <strong>software platform</strong> (a tool you use), not a <strong>professional service</strong> (advice from experts). Think of it like the difference between buying a calculator vs. hiring an accountant."
                }
            },
            "natureOfSoftware": {
                "title": "3. Nature of Software Output",
                "automatedCalculations": {
                    "title": "3.1 Automated Calculations",
                    "text": "All calculations, tax computations, financial ratios, and numerical outputs are generated by programmed algorithms based on the data you input. The software does not \"understand\" your business context, apply professional judgment, or adapt to unique circumstances beyond its programmed logic."
                },
                "reportsAndDocuments": {
                    "title": "3.2 Reports and Documents",
                    "text": "Financial statements, tax reports, and other generated documents are templates populated with your data. They are NOT prepared by professional accountants, NOT reviewed for accuracy or compliance, and NOT certified or audited."
                },
                "taxFeatures": {
                    "title": "3.3 Tax Features",
                    "text": "Tax calculation features are based on general tax rules and rates you configure. They do NOT:",
                    "points": [
                        "Consider all possible tax laws, exemptions, or special provisions",
                        "Interpret complex tax regulations or case law",
                        "Provide tax planning strategies or optimization advice",
                        "Guarantee compliance with tax authorities",
                        "Replace tax preparation by licensed professionals"
                    ]
                },
                "criticalTaxDisclaimer": {
                    "title": "⚠️ CRITICAL TAX DISCLAIMER:",
                    "text": "<strong>Tax laws are complex, jurisdiction-specific, and frequently changing.</strong> You are solely responsible for ensuring tax compliance. TibrCode strongly recommends consulting with licensed tax professionals (CPAs, tax advisors, tax attorneys) for tax matters, especially for tax returns, audits, disputes, or planning."
                }
            },
            "userResponsibilities": {
                "title": "4. User Responsibilities",
                "intro": "As a user of Log & Ledger Pro, YOU are responsible for:",
                "dataAccuracy": {
                    "title": "4.1 Data Accuracy",
                    "text": "Ensuring all data entered into the software is accurate, complete, and up-to-date. The software cannot verify the correctness of your inputs."
                },
                "professionalConsultation": {
                    "title": "4.2 Professional Consultation",
                    "text": "Consulting with qualified, licensed professionals (accountants, CPAs, tax advisors, lawyers, auditors) for:",
                    "points": [
                        "• Accounting methods and standards (GAAP, IFRS)",
                        "• Tax planning, preparation, and filing",
                        "• Compliance with local, national, and international regulations",
                        "• Financial audits and attestation services",
                        "• Legal interpretation and contracts",
                        "• Complex transactions or business structures"
                    ]
                },
                "verificationOfOutputs": {
                    "title": "4.3 Verification of Outputs",
                    "text": "Reviewing and verifying all reports, calculations, and outputs before relying on them for business decisions, tax filings, financial reporting, or regulatory compliance."
                },
                "legalCompliance": {
                    "title": "4.4 Legal and Regulatory Compliance",
                    "text": "Ensuring compliance with all applicable laws, regulations, accounting standards, tax codes, and reporting requirements in your jurisdiction. This includes but is not limited to:",
                    "points": [
                        "• Tax filing deadlines and requirements",
                        "• Financial reporting standards",
                        "• Data protection and privacy laws",
                        "• Industry-specific regulations",
                        "• Anti-money laundering (AML) compliance",
                        "• Know Your Customer (KYC) obligations"
                    ]
                },
                "businessDecisions": {
                    "title": "4.5 Business Decisions",
                    "text": "Making informed business decisions based on professional advice and your own analysis, not solely on software outputs."
                }
            },
            "noWarranties": {
                "title": "5. No Warranties or Guarantees",
                "disclaimer": {
                    "title": "DISCLAIMER OF WARRANTIES:",
                    "text": "THE SOFTWARE IS PROVIDED \"AS IS\" WITHOUT WARRANTIES OF ANY KIND. TIBRCODE DOES NOT WARRANT:",
                    "points": [
                        "That calculations, reports, or outputs will be accurate, complete, error-free, or suitable for your purposes",
                        "That the software complies with all accounting standards, tax laws, or regulations in your jurisdiction",
                        "That use of the software will result in tax compliance, regulatory compliance, or avoidance of penalties",
                        "That the software will meet your specific business needs or expectations",
                        "That the software is appropriate for your particular circumstances without professional consultation",
                        "That third-party integrations or external data sources are accurate or reliable"
                    ]
                },
                "noGuarantee": {
                    "title": "5.1 No Guarantee of Compliance",
                    "text": "TibrCode does NOT guarantee that using the software will ensure compliance with:",
                    "points": [
                        "Generally Accepted Accounting Principles (GAAP)",
                        "International Financial Reporting Standards (IFRS)",
                        "Local accounting standards",
                        "Tax laws and regulations",
                        "Industry-specific compliance requirements",
                        "Audit standards"
                    ]
                },
                "limitations": {
                    "title": "5.2 Software Limitations",
                    "text": "Software has inherent limitations: bugs may exist, features may not work as expected, calculations may contain errors, and the software cannot replace human professional judgment, expertise, or contextual understanding."
                }
            },
            "limitationOfLiability": {
                "title": "6. Limitation of Liability",
                "importantLimitation": {
                    "title": "IMPORTANT LEGAL LIMITATION:",
                    "text": "TO THE MAXIMUM EXTENT PERMITTED BY LAW, TIBRCODE SOFTWARE DEVELOPMENT SHALL NOT BE LIABLE FOR ANY:",
                    "points": [
                        "<strong>Tax Penalties, Fines, or Interest:</strong> Resulting from incorrect calculations, missed deadlines, or non-compliance",
                        "<strong>Audit Issues:</strong> Tax audits, accounting audits, regulatory examinations, or compliance investigations",
                        "<strong>Financial Losses:</strong> Business losses, lost profits, missed opportunities due to software errors or inaccuracies",
                        "<strong>Legal Disputes:</strong> Lawsuits, regulatory actions, or legal proceedings related to financial reporting or compliance",
                        "<strong>Professional Fees:</strong> Costs of hiring accountants, lawyers, or consultants to fix errors or resolve issues",
                        "<strong>Data Errors:</strong> Incorrect calculations, reports, or outputs used for decision-making",
                        "<strong>Regulatory Non-Compliance:</strong> Violations of laws, regulations, or standards"
                    ]
                },
                "riskAssumption": "<strong>You assume all risk</strong> associated with using the software for financial management, tax calculations, regulatory compliance, and business decisions. TibrCode is not responsible for consequences of your reliance on software outputs without professional verification."
            },
            "professionalRecommendations": {
                "title": "7. Professional Consultation Strongly Recommended",
                "whenToConsult": {
                    "title": "🎓 When to Consult Professionals:",
                    "text": "TibrCode <strong>strongly recommends</strong> consulting qualified professionals in these situations:",
                    "points": [
                        "<strong>✓ Tax Matters:</strong> Tax returns, tax planning, audits, disputes, deductions, credits",
                        "<strong>✓ Financial Reporting:</strong> Annual financial statements, audited reports, regulatory filings",
                        "<strong>✓ Business Structure:</strong> Entity formation, mergers, acquisitions, restructuring",
                        "<strong>✓ Compliance:</strong> Industry regulations, international standards, government requirements",
                        "<strong>✓ Complex Transactions:</strong> Multi-currency, international trade, consolidations",
                        "<strong>✓ Legal Contracts:</strong> Partnership agreements, shareholder agreements, loan covenants",
                        "<strong>✓ Strategic Planning:</strong> Business valuations, forecasting, financial analysis",
                        "<strong>✓ Audits:</strong> Internal audits, external audits, compliance audits"
                    ]
                },
                "typesOfProfessionals": {
                    "title": "7.1 Types of Professionals to Consult",
                    "points": [
                        "<strong>Certified Public Accountants (CPAs)</strong> for accounting, auditing, and tax matters",
                        "<strong>Chartered Accountants (CAs)</strong> for financial reporting and auditing",
                        "<strong>Tax Advisors/Tax Attorneys</strong> for tax planning and compliance",
                        "<strong>Financial Advisors</strong> for investment and financial planning",
                        "<strong>Business Attorneys</strong> for legal matters and contracts",
                        "<strong>Industry Specialists</strong> for sector-specific regulations and compliance"
                    ]
                }
            },
            "regulatoryCompliance": {
                "title": "8. Regulatory Compliance Notice",
                "text1": "Financial reporting, tax filing, and business operations are subject to complex and constantly changing laws and regulations that vary by:",
                "points": [
                    "Country and jurisdiction",
                    "State, province, or local municipality",
                    "Industry and business type",
                    "Company size and structure",
                    "Transaction types and volumes"
                ],
                "text2": "Log & Ledger Pro provides general-purpose features and cannot account for all variations, exceptions, and updates to laws and regulations. <strong>You are solely responsible</strong> for ensuring your business operations, financial reporting, and tax compliance meet all applicable requirements."
            },
            "updates": {
                "title": "9. Software Updates and Changes",
                "text": "TibrCode may update, modify, or change the software, features, calculations, or reports at any time without prior notice. While we strive to improve accuracy and functionality, updates may introduce changes that affect your workflows, reports, or calculations. You are responsible for reviewing changes and ensuring continued compliance."
            },
            "thirdParty": {
                "title": "10. Third-Party Services and Integrations",
                "text": "If you use third-party services, integrations, or data sources with Log & Ledger Pro (e.g., bank feeds, payment processors, tax APIs), TibrCode is NOT responsible for the accuracy, reliability, security, or compliance of those third-party services. You use third-party integrations at your own risk."
            },
            "contact": {
                "title": "11. Questions and Contact",
                "text": "For questions about this Disclaimer or the software's capabilities and limitations:",
                "email": "Email",
                "support": "Support",
                "note": "<strong>Note:</strong> Support inquiries are for technical assistance with the software only, not for accounting, tax, legal, or financial advice."
            },
            "footer": {
                "copyright": "© {{year}} TibrCode Software Development. All rights reserved.",
                "binding": "This Disclaimer is a legally binding part of the Terms of Service."
            }
        }
    }

    data['disclaimerPage'] = disclaimer_data

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"Successfully updated {file_path}")

if __name__ == "__main__":
    update_translation()
