spec:
  name: log-ledger-backend
  region: sgp
  services:
  - name: web
    github:
      repo: tibrcode/log-and-ledger
      branch: main
      deploy_on_push: true
    build_command: npm ci
    run_command: node dist/index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    envs:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: "3000"
    - key: DATABASE_URL
      type: SECRET
    - key: FIREBASE_SERVICE_ACCOUNT_KEY
      type: SECRET
    health_check:
      http_path: /
